### ISSUE TITLE
ErrorCode implementation

### ISSUE THREAD

**Issue by C4mperpr0** [olimaye/philander#10]
Extend `systypes.ErrorCode` with an `ErrorCode.ok()` function, that checks whether the given `ErrorCode` is `ErrorCode.errOk` or not. This might seem simple, but will find a lot of use within all implementations, since this can be  used as a drop-in replacement for `err == (systypes.)ErrorCode.errOk`

**Comment by olimaye** [comment]
Suggest the name to be ErrorCode.isOk()
