### ISSUE TITLE
Rename variables, functions and classes to comply with PEP8

### ISSUE THREAD

**Issue by C4mperpr0** [olimaye/philander#12]
Currently, a lot of names used in philander do not comply with PEP8 convention. This is due to backwards compatibility with previous implementations. Still it could be discussed, which names could be exempt from this and thus could be changed. This can especially apply for local or private names and function parameters.

**Comment by olimaye** [comment]
For function names, mixedCase (CamelCaps starting with lower case) is the prevailing style and should be followed furtheron.
